"""Signal A — LLM classification via Groq.

Captures holistic semantic/stylistic coherence: the things a reader intuits (voice, cliche
density, structural predictability) that are hard to reduce to counting.

`classify_with_llm` never raises to its caller. If the API key is missing, the network call
fails, or the response can't be parsed, it degrades gracefully to {"available": False} so the
pipeline can fall back to stylometry-only (with reduced confidence) per planning.md.
"""

import json
import os

from dotenv import load_dotenv

load_dotenv()

MODEL = "llama-3.3-70b-versatile"

_SYSTEM_PROMPT = (
    "You are an expert detector of AI-generated text. You will be given a passage and must "
    "judge the probability that it was generated by an AI language model (as opposed to "
    "written by a human). Weigh holistic signals: voice and idiosyncrasy, cliche and hedging "
    "density, structural predictability, and whether the writing shows lived, specific detail. "
    "Respond ONLY with strict JSON of the form "
    '{"p_ai": <number between 0 and 1>, "rationale": "<one sentence>"}. '
    "p_ai near 1 means almost certainly AI-generated; near 0 means almost certainly human."
)


def _clamp01(x: float) -> float:
    return max(0.0, min(1.0, x))


def classify_with_llm(text: str) -> dict:
    """Return the Groq LLM signal for `text`.

    Returns a dict:
      {
        "available": bool,        # False => signal could not run; exclude from combination
        "p_ai": float | None,     # probability text is AI-generated, in [0, 1]
        "rationale": str | None,  # one-sentence justification from the model
        "model": str,
        "error": str | None,
      }
    """
    result = {
        "available": False,
        "p_ai": None,
        "rationale": None,
        "model": MODEL,
        "error": None,
    }

    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        result["error"] = "GROQ_API_KEY not set"
        return result

    try:
        # Imported lazily so the module loads even if the package is absent.
        from groq import Groq

        client = Groq(api_key=api_key)
        completion = client.chat.completions.create(
            model=MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )
        raw = completion.choices[0].message.content
        data = json.loads(raw)
        p_ai = _clamp01(float(data["p_ai"]))

        result["available"] = True
        result["p_ai"] = p_ai
        result["rationale"] = data.get("rationale")
    except Exception as exc:  # network, auth, JSON, or schema failure -> graceful fallback
        result["error"] = f"{type(exc).__name__}: {exc}"

    return result


if __name__ == "__main__":
    # Independent self-test: run a few inputs and inspect the output before wiring into
    # the endpoint.  Usage:
    #   .venv/bin/python -m signals.llm
    #   GROQ_API_KEY= .venv/bin/python -m signals.llm   # exercises the fallback path
    samples = {
        "clearly_ai": (
            "Artificial intelligence represents a transformative paradigm shift in modern "
            "society. It is important to note that while the benefits of AI are numerous, it "
            "is equally essential to consider the ethical implications. Furthermore, "
            "stakeholders across various sectors must collaborate to ensure responsible "
            "deployment."
        ),
        "clearly_human": (
            "ok so i finally tried that new ramen place downtown and honestly? underwhelming. "
            "the broth was fine but they put WAY too much sodium in it and i was thirsty for "
            "like three hours after. probably won't go back unless someone drags me there"
        ),
        "borderline": (
            "I've been thinking a lot about remote work lately. There are genuine tradeoffs "
            "— flexibility and no commute on one side, isolation and blurred work-life "
            "boundaries on the other. Studies show productivity varies widely by individual."
        ),
    }
    for name, sample in samples.items():
        out = classify_with_llm(sample)
        print(f"\n=== {name} ===")
        print(json.dumps(out, indent=2))
